- hosts: localhost
  vars_files:
    - vars/secret.yml
  tasks:
    - name: test that my module works
      todo:
        api_key: "{{ key }}"
        content: "This was created by Ansible"
      register: result

    - debug: var=result