---
- hosts: localhost
  vars_files:
    - vars/secret.yml
  tasks:
    - name: test module using every option
      todo:
        api_key: "{{ key }}"
        content: This was created by ansible
        date: today
        priority: 1
        indent: 1
        labels:
          - small
          - medium
          - large
      register: result

    - debug: var=result
...